sudo: false

language: node_js
node_js:
  - node # latest stable

env:
  - ELM_VERSION=0.18.0 ELM_TEST_VERSION=0.18.2

cache:
  directories:
    - sysconfcpus

install:
  # Travis exposes a few more CPUs (like... 14 more) than the code can actually
  # use. This program allows us to lie to the compiler about how many CPUs it
  # can use. In this case, we're actually telling the truth about the number of
  # usable CPUs, so build times go way down.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

  - npm install -g elm@${ELM_VERSION} elm-test@${ELM_TEST_VERSION}
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm package install --yes
  - cd examples; ../elm-ops-tooling/with_retry.rb elm package install --yes; cd ..

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm make
  - cd examples; for example in *.elm; do elm make $example; done; cd ..
  - elm-test
